from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from datetime import datetime
import os


# ---------------- VISUAL DECORATORS (NO LOGIC IMPACT) ----------------

def _draw_page_border(canvas, doc):
    width, height = A4
    margin = 12 * mm

    canvas.saveState()
    canvas.setLineWidth(1)
    canvas.rect(
        margin,
        margin,
        width - 2 * margin,
        height - 2 * margin
    )
    canvas.restoreState()


def _draw_header_footer(canvas, doc):
    width, height = A4

    canvas.saveState()

    # ---------- HEADER ----------
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(
        20 * mm,
        height - 18 * mm,
        "BEACON – Behavioral Backdoor Detection Report"
    )

    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        width - 20 * mm,
        height - 18 * mm,
        f"Generated: {doc._beacon_generated_on}"
    )

    canvas.setLineWidth(0.5)
    canvas.line(
        20 * mm,
        height - 20 * mm,
        width - 20 * mm,
        height - 20 * mm
    )

    # ---------- FOOTER ----------
    canvas.setFont("Helvetica", 8)
    canvas.drawString(
        20 * mm,
        15 * mm,
        "Generated by BEACON Framework"
    )

    canvas.drawRightString(
        width - 20 * mm,
        15 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()


def _decorate_page(canvas, doc):
    _draw_page_border(canvas, doc)
    _draw_header_footer(canvas, doc)


# ---------------- MAIN REPORT FUNCTION ----------------

def generate_pdf_report(report_data, filename=None, output_dir="reports"):
    """
    Generates a BEACON forensic PDF report.

    :param report_data: Dictionary containing analysis results
    :param filename: Optional explicit filename (e.g., BEACON_report_<PID>.pdf)
    :param output_dir: Directory to store reports
    :return: Full path to generated PDF
    """

    os.makedirs(output_dir, exist_ok=True)

    # Filename logic (timestamp-based)
    if not filename:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"BEACON_report_{timestamp}.pdf"

    filepath = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4)
    doc._beacon_generated_on = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    styles = getSampleStyleSheet()
    elements = []

    # ---------------- TITLE ----------------
    elements.append(Paragraph(
        "<b>BEACON – Behavioral Backdoor Detection Report</b>",
        styles["Title"]
    ))
    elements.append(Spacer(1, 20))

    # ---------------- METADATA ----------------
    elements.append(Paragraph(
        f"<b>Date & Time:</b> {report_data.get('timestamp')}",
        styles["Normal"]
    ))

    if report_data.get("pid") is not None:
        elements.append(Paragraph(
            f"<b>Runtime Process ID (PID):</b> {report_data.get('pid')}",
            styles["Normal"]
        ))

    elements.append(Spacer(1, 12))

    # ---------------- SAMPLE INFO ----------------
    elements.append(Paragraph("<b>Sample Information</b>", styles["Heading2"]))
    elements.append(Paragraph(
        f"Executable Path: {report_data.get('sample_path')}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # ---------------- EVIDENCE INFO ----------------
    elements.append(Paragraph("<b>Evidence Information</b>", styles["Heading2"]))
    elements.append(Paragraph(
        f"SHA-256: {report_data.get('sha256')}",
        styles["Normal"]
    ))
    elements.append(Paragraph(
        f"MD5: {report_data.get('md5')}",
        styles["Normal"]
    ))
    elements.append(Paragraph(
        f"File Size: {report_data.get('file_size')} bytes",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # ---------------- BEHAVIORAL FEATURES ----------------
    elements.append(Paragraph("<b>Observed Behavioral Features</b>", styles["Heading2"]))
    elements.append(Paragraph(
        f"Process Count: {report_data.get('process_count')}",
        styles["Normal"]
    ))
    elements.append(Paragraph(
        f"Network Connections: {report_data.get('network_connections')}",
        styles["Normal"]
    ))
    elements.append(Paragraph(
        f"Persistence Detected: {'Yes' if report_data.get('persistence') else 'No'}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # ---------------- DETECTION RESULTS ----------------
    verdict = report_data.get("heuristic_result")
    if verdict == "BENIGN":
        verdict = "SAFE"

    elements.append(Paragraph("<b>Detection Results</b>", styles["Heading2"]))
    elements.append(Paragraph(
        f"Heuristic Verdict: <b>{verdict}</b>",
        styles["Normal"]
    ))

    elements.append(Paragraph(
        f"Threat Classification: {report_data.get('threat_type')} "
        f"(Confidence: {report_data.get('threat_confidence')})",
        styles["Normal"]
    ))

    elements.append(Paragraph(
        f"Risk Level: <b>{report_data.get('risk_level')}</b>",
        styles["Normal"]
    ))

    elements.append(Paragraph(
        f"Reason: {report_data.get('heuristic_reason')}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 12))

    # ---------------- ANALYST NOTES ----------------
    elements.append(Paragraph("<b>Analyst Notes</b>", styles["Heading2"]))

    analyst_notes = report_data.get("analyst_notes")
    if analyst_notes:
        elements.append(Paragraph(analyst_notes, styles["Normal"]))
    else:
        elements.append(Paragraph(
            "No analyst notes were provided for this analysis.",
            styles["Normal"]
        ))

    elements.append(Spacer(1, 12))

    # ---------------- BEHAVIOR TIMELINE ----------------
    elements.append(Paragraph("<b>Behavior Timeline</b>", styles["Heading2"]))
    for line in report_data.get("behavior_timeline", "").split("\n"):
        elements.append(Paragraph(line, styles["Normal"]))

    elements.append(Spacer(1, 12))

    # ---------------- CHAIN OF CUSTODY ----------------
    elements.append(Paragraph("<b>Chain of Custody</b>", styles["Heading2"]))

    custody_text = report_data.get("chain_of_custody", "")
    for line in custody_text.split("\n"):
        elements.append(Paragraph(line, styles["Normal"]))

    elements.append(Spacer(1, 12))


    # ---------------- CONCLUSION ----------------
    elements.append(Paragraph("<b>Conclusion</b>", styles["Heading2"]))
    elements.append(Paragraph(
        "The analyzed executable was evaluated using dynamic behavioral analysis. "
        "A verdict of SAFE indicates that no suspicious behavior was observed during "
        "the monitored execution window. SAFE does not imply that the file is trusted, "
        "benign in all contexts, or free from dormant, time-triggered, or logic-based "
        "malicious behavior. Final determination should be made by a forensic analyst "
        "in conjunction with additional evidence and context.",
        styles["Normal"]
    ))

    doc.build(
        elements,
        onFirstPage=_decorate_page,
        onLaterPages=_decorate_page
    )

    return filepath
